# Generated by Django 4.0.3 on 2022-04-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ankeansite', '0002_playlist_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='tag',
            field=models.CharField(default='', max_length=70),
        ),
    ]
